### PR TITLE
Add openscope_databook notebook

### PR DESCRIPTION
**Pull request by jeromelecoq**
This pull request introduces a notebook developed from the OpenScope databook. It is self contained and should run end-to-end. 
It introduces fitting a Cebra-time embedding, including a grid-search, to one dataset hosted on Dandi Archive. 

We will continue update this to match our corresponding notebook on https://github.com/AllenInstitute/openscope_databook

We welcome any feedbacks and comments!

### CODE REVIEW

**Comment by MMathisLab** [comment]
Very nice PR, thank you @jeromelecoq ! 
- I think already a great contribution to show OpenScope data loading and grid searching! 
- Maybe one thing to add would be a plot that compares the loss value for best parameters trained across variables, and perhaps downsteaming decoding, namely I am thinking about something like these plots: 

https://cebra.ai/docs/cebra-figures/figures/ExtendedDataFigure5.html

Screen Shot 2023-08-18 at 12 44 17 PM

Screen Shot 2023-08-18 at 12 44 29 PM

**Comment by jeromelecoq** [comment]
Thank you for your comments. As you suggested, I added a KNN decoder, with 10-fold measure of R2. The notebook then plot the frame decoding abilities across movies. This was the key question in the original study and is therefore relevant scientifically. 

I did not add the loss plot you suggested across trainings because our evaluation of the models was across too many parameters and the plot were too busy. However, the notebook does include a bar plot of the final loss values across training parameters.

**Comment by jeromelecoq** [comment]
@MMathisLab just for awareness

**Comment by MMathisLab** [comment]
Hi @jeromelecoq sorry for the delay. So I attempted a few tiny fixes (see edits), and then running notebook. 

However, I ran into issues. 

If I just run the notebook top to bottom, this isn't possible right now as main items are not defined: 

(1) seems to load, but issues with data perhaps?

Screen Shot 2023-09-08 at 3 11 00 PM

(2) Errors:


Screen Shot 2023-09-08 at 3 11 10 PM

Let me know what you think!

**Comment by MMathisLab** [comment]
Hey @jeromelecoq thanks for this, and sorry for the delay! I made a few minor edits, and also tried to run locally, but I hit issues, namely:

everything installs, I restarted kernel, import and there are some missing def):


Screen Shot 2023-09-08 at 3 20 44 PM

So I would suggest to edit this cell to include the import: `from dandi_utils import dandi_download_open`

like so:

Screen Shot 2023-09-08 at 3 24 37 PM


as then I hit no errors :)

**Comment by MMathisLab** [comment]
so @jeromelecoq if you are OKAY with my edits, LGTM! Thanks for this contribution!!

**Comment by nastya236** [comment]
Hey @jeromelecoq! Thank you for your contributions. I appreciate your work on this PR. Could you kindly provide some clarification on why you've chosen to use only 41 neurons instead of the entire set? In the [paper](https://pubmed.ncbi.nlm.nih.gov/35022186/) you've referenced, it appears that there are over 200 neurons, as indicated in Figure 1. I'm curious to understand the reasoning behind this specific selection.

**Review by MMathisLab — APPROVED** [review]

**Comment by jeromelecoq** [comment]
Sorry I missed these messages. 

1/ I don't know how this import got away. I apologize for that. 

2/ The modified logo is interesting. We could have embedded the Allen logo inside indeed. 
Our logo is open. I prefer the simpler version for OpenScope but I guess you intend to refer to the Allen. I support all sorts of creativity here. 

3/ Regarding neurons numbers. This notebook is running on a single session which happened to have fewer neurons. A next step is indeed to run this notebook across ALL of our sessions of that set of experiments which which were across way more neurons, probably 10s of thousands. Anybody is welcome to try it since our entire code + data is available :-)
We might do it too if time permits.

**Comment by nastya236** [comment]
Great! Do you have this data available with dandi as well? I am up too work with it:)

**Comment by jeromelecoq** [comment]
Yes

**Comment by MMathisLab** [comment]
Fab, thanks! Maybe @nastya236 is wondering if you have a pointer/link to the largest dataset possible for this setting - she's keen to play around 😊

**Comment by jeromelecoq** [comment]
I think there is very interesting science to be done by scaling up this notebook across all sessions. I suspect the entire meaningful paper could be redone with CEBRA, which is why we chose this dataset. I am not bothered at all if anybody embarks on this.

**Comment by jeromelecoq** [comment]
> Fab, thanks! Maybe @nastya236 is wondering if you have a pointer/link to the largest dataset possible for this setting - she's keen to play around 😊

Ah, I think you meant within this particular set of experiment, which one with the largest number of neurons. I might have misunderstood. If that is the question, then I suggest to use this other notebook which creates a table of all experiments. https://alleninstitute.github.io/openscope_databook/basics/get_dandiset_metadata.html
You might have to point it at this dandiset but I believe it should work. 

It is a bit slower as it pulls all NWB but you would have to do it once anyway.

**Pull request merged**
