### PR TITLE
Add consistency scores for Demo_hippocampus_multisession.ipynb

### PR DESCRIPTION
**Pull request by gonlairo**
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/issues/512

Regarding your comment of using `adapt = True`, afaik it is not implemented in multi-animal training.

### CODE REVIEW

**Comment by MMathisLab** [comment]
here we can also adapt the data loader, thanks @gonlairo !

**Comment by MMathisLab** [comment]
@gonlairo can you resolve conflicts and add the data-loading? thanks! cc @stes

**Review by MMathisLab — CHANGES_REQUESTED** [review]
- please adapt for data loading and merge conflicts

**Comment by gonlairo** [comment]
> * please adapt for data loading and merge conflicts

what do you mean by data loading? the automatic download of datasets?

**Comment by stes** [comment]
image

remove warning (by installing `datasets`)

**Review by MMathisLab — APPROVED** [review]

**Pull request merged**
